# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jmx:
    enabled: false
  main:
    banner-mode: OFF
  lifecycle:
    timeout-per-shutdown-phase: 20s

  # ====================================================================================================================
  # = JACKSON
  # ====================================================================================================================
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Amsterdam

# ======================================================================================================================
# = WEB SERVER
# ======================================================================================================================
server:
  port: 8081
  shutdown: graceful

# ======================================================================================================================
# = OPEN API
# ======================================================================================================================
springdoc:
  swagger-ui:
    path: /v3/swagger-ui.html

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  level:
    root: INFO
    org:
      springframework:
        transaction:
          interceptor: TRACE
        aop:
          interceptor: TRACE

# ======================================================================================================================
# = ACTUATOR - ALL METRICS OVER HTTP INSTEAD OF JMX
# ======================================================================================================================
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: '*'


# ======================================================================================================================
# = AXON
# ======================================================================================================================
axon:
  metrics:
    auto-configuration:
      enabled: true
